API_BUY_ITEMS = "/stores/products/items/buy"
API_BUY_ITEMS_FROM_BASKET = "/stores/products/items/buy_from_basket"
API_BOOKING = "/booking"
API_EVENTS = "/users/events"
INVALID_BUSKET_MONEY_COUNT = "Недостаточно денег на счету"
