REPOSITORY_USERS = "users"

ROLE_CUSTOMER = 1
ROLE_SELLER = 2
ROLE_ADMIN = 3
ROLE_BOT = 4

DEFAULT_LIMIT = 100
DEFAULT_OFFSET = 0
VALUE_NOT_LESS = 0
DEFAULT_COUNT_TAGS = 5

METHOD_ADD = "add"
METHOD_GET_BY_ID = "get_by_id"
METHOD_GET = "get"
METHOD_UPDATE = "update"
METHOD_DELETE = "delete"

EXPIRES_HOUR_CACHE_ON_SECONDS = 3600
EXPIRES_10_MIN_CACHE_ON_SECONDS = 600

PREFIX_REDIS_CACHE = "fastapi-cache-hack"
BACKEND_NAME = "Backend MISty"
MAIN_QUEUE_NAME_CELERY = "hack-tasks"


